### ISSUE TITLE
Adding DRM to this anticheat

### ISSUE THREAD

**Issue by MWHunter** [retrooper/meow-anticheat#5]
I'd like to thank you for finally open sourcing this anticheat, it will be inspirational to all other Skript anticheat developers.  However, I believe you should obfuscate the skript so that it cannot be taken and analyzed by cheat devs.  You can do this by using a Skript to Jar converter, and then obfuscating the resulting jar!

**Comment by retrooper** [comment]
I am already doing it in Meow anticheat premium, I convert Skript to Javascript(AKA Java).
